### ISSUE TITLE
spack packages for latest swift, MPIX Launch

### ISSUE THREAD

**Issue by bd4** [CODARcode/cheetah#10]
In order to make using Cheetah for the 0.1 release as easy as possible, we would like to have spack packages for all it's dependencies.

**Comment by kshitij-v-mehta** [comment]
It would be great if @jmjwozniak could edit the existing spack package for stc and add the develop target that will make spack fetch the HEAD from the swift repo, instead of fetching a stable version. That way, he can update the swift repo and not update the spack package every time. For now, this should work as a good solution.

**Comment by bd4** [comment]
The way the build system and spack packages are structured, I don't think all necessary files and structure exist in github. The other issue with github builds is the need to use `--no-checksum`.

**Comment by bd4** [comment]
It is not obvious what value of nprocs we should pass to turbine for each group run. My best guess is to use the max across all instances in the group, where the value for each instance is the sum of the nprocs for each code.
