### ISSUE TITLE
Status reporting needs to be updated to read multi-line fobs.json

### ISSUE THREAD

**Issue by kshitij-v-mehta** [CODARcode/cheetah#152]
fobs.json was updated in #147 to be a multi-line array of json dicts, instead of a dict per line. The status reporting tool in Cheetah needs to be updated so that it can read the updated file.

**Comment by bd4** [comment]
The reason I initially used JSON document per line was to support more dynamic workloads, e.g. decide on future jobs based on results of previous job. This is a use case that @jmjwozniak had. In the current iteration of Cheetah it's definitely static, but something to consider for future.

**Comment by kshitij-v-mehta** [comment]
Could you say a little more on how having a JSON document per line helps with dynamic workloads? It will help me understand better and design accordingly.

**Comment by bd4** [comment]
The idea we had is that instead of reading from a file, the workflow script could be reading data from a socket, and have an interactive session with another service that is processing results and deciding what jobs to send next. I was thinking that rather than having two different input protocols, both the file and socket processors could use independent JSON documents per FOB. The other downside to a JSON list is that most parsers (including the one in Python standard lib if memory services) have to read the entire document before providing any data. Only an issue for very very large FOB lists, but one JSON document per line does allow processing the FOBs as each line is read and parsed.

I think for current use cases, it doesn't really matter, and is probably easy enough to adjust the format according to new use cases when they become more real. Just something to keep in mind, I wanted to make sure the thinking around this got captured somewhere.

**Comment by kshitij-v-mehta** [comment]
Ok, thanks.

**Comment by kshitij-v-mehta** [comment]
Fixed in https://github.com/CODARcode/cheetah/commit/ee31e492720dc48f2f7ec0c0aa2da27051e31ae3
