### ISSUE TITLE
Ideas for a more powerful Cheetah

### ISSUE THREAD

**Issue by ianfoster** [CODARcode/cheetah#22]
Currently Cheetah runs each run of a code as a separate job on the target computer. This approach has limitations with respect to throughput as a) each run must be scheduled separately, and b) multiple run cannot be performed concurrently.

A more powerful Cheetah would be able to perform multiple runs in a single "job" (or in multiple jobs), executing multiple runs at the same time and/or one after the other. So e.g. with an allocation of 8 nodes, it could perform runs in sequence that require 1, 2, 4, 8 nodes, or that use the same number of nodes but with different options. Or, it could performs 4 x 2-node, 2 x4-node, 1 x 8-node runs.

To do this well, it would require mechanisms for starting, monitoring (to detect termination), and controlling (e.g., to stop after a time limit) sets of runs.

I believe that the required mechanisms exist within Swift. According to Justin:

-- It is straightforward to start runs one after the other, or at the same time, within a single "job" with the current launch mechanism.

-- The current launch() mechanism can detect failure of a run but does not currently have a timeout. [Justin observes: "We could add one pretty easily.  CANDLE has this problem so they use Keras callback functions to cleanly shut down after given durations."]

Note that these mechanisms are very similar to those required for deep learning and other applications.

**Comment by bd4** [comment]
Can you clarify what you mean by 'experiment'? Do you mean a campaign, or single run of the application within the campaign? Currently Cheetah sets PPN (processes per node) based on the number of nodes set for the SweepGroup, i.e. PPN = ceil((total processes per application run) / (# of nodes)). This means only one application run will happen at a time. If we allow the campaign writer to set PPN themselves, it would be more flexible. Or perhaps they should be able to set number of concurrent application runs, and Cheetah figures out PPN? I'm not sure how best to organize it, because I don't have much experience running real campaigns on real applications yet.

Re multiple allocations, do you mean multiple PROJECTs? Is that really useful in practice?

**Comment by bd4** [comment]
My understanding is that if Cheetah set the number of processes for swift-t to a higher value, it would allow it to execute multiple runs in parallel. E.g. if a run heat transfer run uses 12 (heat) + 2 (stage) + 1 (swift) = 15 processes, and we allowed it to use 45, it should be able to do 3 runs in parallel. I think with the way launch_multi works, this would work out, i.e. it would run them together and not try to run a bunch of stage instances without the matching heat instances.

Re multiple scheduler jobs, the initial support is already there, each SweepGroup in the campaign definition is designed to be a different scheduler job and can have a different number of nodes.

**Comment by ianfoster** [comment]
I updated my note to be clear that I meant "run" when I said "experiment"

**Comment by jmjwozniak** [comment]
The examples here should illustrate how to do this: https://github.com/CODARcode/SwiftExamples/tree/master/cheetah-22

I will try the timeout thing now...

**Comment by jmjwozniak** [comment]
The timeout feature is in, an example is in c.swift here: https://github.com/CODARcode/SwiftExamples/tree/master/cheetah-22
