### ISSUE TITLE
Resume partially completed campaigns

### ISSUE THREAD

**Issue by kshitij-v-mehta** [CODARcode/cheetah#37]
A campaign may not complete in the time requested by the user, as it may not be possible to make an accurate estimate of the time required to run the full campaign beforehand. Users must have the ability to resume a campaign that did not finish due to insufficient time requested.

**Comment by bd4** [comment]
This should be straightforward once we add top level progress tracking, as long as the file that contains the progress is easily machine parsable.

Note that this also interacts with #33 , since the progress file will need to be updated to indicate that the new groups have not run.

**Comment by bd4** [comment]
Should this only consider jobs that were killed because of the timeout? What if some runs fail with non-zero exit status of one or more component for another reason?

**Comment by ianfoster** [comment]
In my view we should not rerun jobs that failed because of a non-zero exit status. Perhaps later one might want to add an option to retry failed jobs, but keep it simple for now.

**Comment by kshitij-v-mehta** [comment]
I agree with Ian, we should only run jobs that were never run in the first place due to the job running out of time.

**Comment by bd4** [comment]
Ok, so first version is resume with FOBs that were never even started. If a FOB was started and reached it's per-run timeout and was killed, or if it was killed because of reaching the scheduler job walltime limit, it will not be re-run. The latter case, killed by scheduler, might be fairly easy to detect, by having workflow mark when runs are 'done' (with no regard to fail/success/timeout), and that could be re-run as well, as a slight refinement.

**Comment by bd4** [comment]
I'm thinking this should primarily be a workflow script feature. The state is already there in some form: existence of a 'codar.cheetah.return.{code}' file for each code in the FOB in the run directory indicates the run is 'done'. If passed a `--resume` option, workflow could skip any run for which these files are present. One question: what should happen if one or more of the codes can't be run, e.g. the executable does not exist or has wrong permission?

**Comment by kshitij-v-mehta** [comment]
One way to know if an experiment is run is to look at the 'codar.cheetah.return.{code}' file. Another option would be to write a file when an experiment is started. If now the job crashes if the executable did not have the correct permissions, we know that the experiment did start since a file was written when it was started.

**Comment by mw70** [comment]
I can imagine trying to deal with the FOB execution states as being on of 4 bins:  

0 -> needs to run
1 -> completed
2 -> scheduled but not complete (could also mean stopped by time)
<0 -> -1*(value) is the error code that was returned.

If the dispatcher is restarting from a run that was stopped due to time, the first thing you do is walk the list of existing experiments, reset any 2's to 0's, and then start popping 0's to execute them.  Anything less than zero you'd skip.

Does that make sense?

**Comment by kshitij-v-mehta** [comment]
I agree with this approach, and once all sweeps within a sweep group are completed, we could even mark the group as `1 (completed)`. A status file could be maintained in every run dir, or a single status file at the top-level campaign dir (we can think about that later since this is more of an implementation detail).

I am just wondering if there is a way to know why a run crashed. How do we know if a run crashed because it ran out of time, or because it segfaulted? Does it require parsing the output log file for keywords such as 'walltime limit reached' or 'segmentation fault' etc.?

**Comment by bd4** [comment]
The return value of the executable is saved in `codar.cheetah.{CODE}.return`, if it's killed by workflow because of the per-run timeout, it will be -9. Not sure what it will be if killed by scheduler, probably -9 or -15 (term), would need to parse the log file to be sure, or add a more machine parsable indicator. It should be -11 for segfault.

**Comment by mw70** [comment]
As a (maybe) useful observation, this is exactly the logic that lives at the heart of any of the master-worker scheduler processes.  With a quick google of "python master worker framework" there were several interesting hits.  We want something that is both concurrent and resumable... but if we can borrow something reasonably standard and just adapt it to the HPC environment, I think it might be a good choice.

**Comment by bd4** [comment]
Latest spec: workflow script maintains a sweep group level status file, `codar.workflow.status.json`, with keys that are the run subdirectories (run-XXX), and values that are enum strings `not_started`, `running`, 'timeout`, `succeeded`, or `failed`. If the file doesn't exist yet, it means the workflow script has never been run (all are `not_started`. It will be written out in full each time there is a state change, subject to an internal (in-memory) lock which should be fine if the number of runs in the group is not super large (will likely need to evolve into something more random access in future). timeout=finished because it hit the per-run timeout, succeeded=all codes had zero exit status, failed=one or more code had nonzero exit.

**Comment by bd4** [comment]
Challenges: workflow doesn't know how many runs there are at the start, it accepts them from producer as resources free up. It was designed this way to support dynamic job flows, possibly submitted over a socket, in response to results of previous jobs. This is a use case for some swift related work. For the purposes of a post-processing script that collects results and needs to know which directories to skip, this isn't too much of a problem - the script could just ignore anything that is not in the file, because it will be in `non_started` state. For keeping track of N/M runs complete, it is an issue. Maybe workflow could accept optional arg with total number of jobs. Or cheetah could write that out to a file, and a status script could infer based on completed jobs in workflow state file plus the total file.

**Comment by bd4** [comment]
To make matters even more confusing, you could have a FOB where each component runs in a different directory. I like the idea of introducing a first classing notion of a FOB id, which could be assigned by the producer/generator (cheetah or swift) or the consumer (workflow itself). Then the status file could use those ids. Currently workflow maintains this internally as the `pipeline_id`, but it's not correlated to anything in the FOB.

**Comment by kshitij-v-mehta** [comment]
> For keeping track of N/M runs complete, it is an issue

Not sure I understand this clearly. Do you mean to say that we cannot know the total no. of jobs, as the status file only contains information about jobs when they start? Possible option is to create the status file and populate all runs with `not_started` when cheetah creates the campaign dir hierarchy

**Comment by bd4** [comment]
Maybe workflow should become more greedy about reading all available pipelines. That would also allow it to more intelligently schedule, even in a situation when new pipelines are added dynamically. For example, in exaalt there are jobs of different sizes, and if they are all running in the same SweepGroup/scheduler group, the smaller sizes need to be matched with the bigger sizes to fit. Basically the 'find new job' logic should be find the biggest job less than or equal to available resources.

**Comment by bd4** [comment]
My latest version looks like this:
```
  "8": {
    "state": "done",
    "reason": "succeeded",
    "return_codes": {
      "code01": 0,
      "code02": 0
    }
  },
  "9": {
    "state": "done",
    "reason": "succeeded",
    "return_codes": {
      "code01": 0,
      "code02": 0
    }
  }
```

The idea here is that 'state' is a strict enum that can never change, either 'not_started', 'running', or 'done'. 'reason' is a non-strict enum that can evolve, and how we classify success vs failure may evolve. This is something we ran into with globus. I'm not sure if this is the best way of framing it, but I think it's better than trying to make success and failure part of the strict status enum.

**Comment by kshitij-v-mehta** [comment]
Ok, looks good to me.

**Comment by kshitij-v-mehta** [comment]
Completed in PR #130 .

**Comment by kshitij-v-mehta** [comment]
Now the default behavior in Cheetah is that when a user submits a campaign, it submits a job only if there are experiments in the group that are not yet run. If the campaign is complete, re-submitting the campaign makes Cheetah print a message and quit.

When a campaign/sweep_group is submitted, Cheetah looks for the run status 'not_started' in a group. 
If a user re-submits a group that is already running, Cheetah could submit the same group again, which could lead to the same experiments being run as part of two different jobs.
