### ISSUE TITLE
Parameters of type `ParamAdiosXML` not included in fob json files

### ISSUE THREAD

**Issue by kshitij-v-mehta** [CODARcode/cheetah#78]
Files `fobs.json` in the sweep-group directory, and `codar.cheetah.fob.json` in the run directory do not include parameters of the type `ParamAdiosXML`.

**Comment by bd4** [comment]
The fob currently only contains the information related to how workflow will run the app - since ParamAdiosXML transforms an input file when setting up the experiment, it's not needed, and not clear where it would go in the fob. The codar.cheetah.run-params.json does have it, and is more appropriate for post processing use I think. But it does pose some questions: should the fob embed a dict of the all the params, so we keep everything consolidated? There could be a special key that workflow is not allowed to use, like 'app_extra' or something. Or alternatively, maybe the run post process script should be passed the path to this file instead of the path to the fob.

**Comment by kshitij-v-mehta** [comment]
In that case, I vote for passing codar.cheetah.run-params.json to the post-processing script.

**Comment by bd4** [comment]
I started implementing this and went to update my existing run post process scripts, and remembered what I was using the fob data for - each code may have used a subdir as it's working directory, see https://github.com/CODARcode/cheetah/blob/master/examples/post-run-rm-staged.py. Maybe we should just pass nothing, and let the script decide which file to load (run-params and/or the fob)? Or we could add working_dir to the run-params.... I think this will need to evolve over time as we see what common run script requirements are, so for now we should just start with something that works for our initial examples, even if it's a little hacky.

**Comment by bd4** [comment]
For now I am passing the run-params file, I think that will be the most common case. The examples load the fob explicitly by name from the working dir.
